# The use of implicit sources has been deprecated.
source 'https://github.com/CocoaPods/Specs.git'
# ignore all warnings from all pods
inhibit_all_warnings!
# Use frameworks instead of static libraries for Pods.
#plugin 'cocoapods-amimono'

use_frameworks!

platform :ios, '10.0'

def all_pods
    #Network
    pod 'Alamofire'#, '~> 4.7'
    pod 'AlamofireNetworkActivityIndicator' #, '~> 2.2'

    pod 'Kingfisher', '~> 4.0'

    pod 'RxSwift'#,    '~> 4.2.0'
    pod 'RxCocoa'#,    '~> 4.2.0'
    pod 'RxAlamofire'

end

target "TestTaskSGPopkov" do
    all_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "4.0"
        end
    end
end

