# The use of implicit sources has been deprecated.
source 'https://github.com/CocoaPods/Specs.git'
# ignore all warnings from all pods
inhibit_all_warnings!
# Use frameworks instead of static libraries for Pods.
#plugin 'cocoapods-amimono'

use_frameworks!

platform :ios, '10.0'

def all_pods
    #Network
    pod 'AlamofireNetworkActivityIndicator'

    pod 'Kingfisher', '~> 4.0'

    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'RxAlamofire'
    pod 'RxKeyboard'
    pod 'RxDataSources', '~> 3.0'

end

target "TestTaskSGPopkov" do
    all_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "4.0"
        end
    end
end

